# -*- coding: utf-8 -*-
"""Assignment 1 Chocolate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qlCpb7bDHh7oPEg-N4BoEMsk3oZJTTla
"""

def distribute_chocolates_iteratively(chocolates, students):
    # Assuming chocolates and students are lists of dictionaries and lists of student names respectively.
    # Distributing chocolates to students iteratively.
    distribution = {}
    for i, student in enumerate(students):
        if i < len(chocolates):
            distribution[student] = chocolates[i]
        else:
            break  # If there are more students than chocolates, stop assigning.

    return distribution

def distribute_chocolates_recursively(chocolates, students, distribution=None, index=0):
    # Base case: If no chocolates left or no students left, return the distribution.
    if distribution is None:
        distribution = {}

    if index >= len(students) or index >= len(chocolates):
        return distribution

    # Assign chocolate to student.
    distribution[students[index]] = chocolates[index]

    # Recursive call for the next student and the next chocolate.
    return distribute_chocolates_recursively(chocolates, students, distribution, index + 1)

# Test cases
chocolates = [{"weight": 5, "price": 2, "type": "Almond", "ID": "002"},
              {"weight": 7, "price": 4, "type": "Peanut butter", "ID": "005"}]
students = ["Andrew", "Nasser", "Ali", "Mohammed"]

# Testing the iterative function
iterative_distribution = distribute_chocolates_iteratively(chocolates, students)
print("Iterative Distribution:", iterative_distribution)

# Testing the recursive function
recursive_distribution = distribute_chocolates_recursively(chocolates, students)
print("Recursive Distribution:", recursive_distribution)

class Chocolate:
    def __init__(self, weight, price):
        self.weight = weight
        self.price = price

    def __repr__(self):
        return f"Chocolate(weight={self.weight}, price={self.price})"

def merge_sort(chocolates, attribute):
    if len(chocolates) > 1:
        mid = len(chocolates) // 2
        left_half = chocolates[:mid]
        right_half = chocolates[mid:]

        merge_sort(left_half, attribute)
        merge_sort(right_half, attribute)

        i = j = k = 0

        while i < len(left_half) and j < len(right_half):
            if getattr(left_half[i], attribute) <= getattr(right_half[j], attribute):
                chocolates[k] = left_half[i]
                i += 1
            else:
                chocolates[k] = right_half[j]
                j += 1
            k += 1

        while i < len(left_half):
            chocolates[k] = left_half[i]
            i += 1
            k += 1

        while j < len(right_half):
            chocolates[k] = right_half[j]
            j += 1
            k += 1

# Example usage:
chocolates = [Chocolate(100, 2), Chocolate(90, 3), Chocolate(110, 1), Chocolate(80, 2.5)]

print("Original List:")
print(chocolates)

# Sort by weight
merge_sort(chocolates, "weight")
print("\nSorted by Weight:")
print(chocolates)

# Sort by price
merge_sort(chocolates, "price")
print("\nSorted by Price:")
print(chocolates)

class Chocolate:
    def __init__(self, weight, price):
        self.weight = weight
        self.price = price

    def __repr__(self):
        return f"Chocolate(weight={self.weight}, price={self.price})"

def find_chocolate_by_attribute(chocolates, attribute, value):
    low = 0
    high = len(chocolates) - 1

    while low <= high:
        mid = (low + high) // 2
        if getattr(chocolates[mid], attribute) == value:
            return mid  # Chocolate found
        elif getattr(chocolates[mid], attribute) < value:
            low = mid + 1
        else:
            high = mid - 1

    return -1  # Chocolate not found

# Example chocolates sorted by weight
chocolates_by_weight = [Chocolate(50, 1.00), Chocolate(60, 1.50), Chocolate(70, 2.00), Chocolate(80, 2.50)]
# Example chocolates sorted by price
chocolates_by_price = [Chocolate(80, 1.00), Chocolate(60, 1.50), Chocolate(50, 2.00), Chocolate(70, 2.50)]

# Searching for a chocolate by weight
weight_to_find = 70
index_found_by_weight = find_chocolate_by_attribute(chocolates_by_weight, 'weight', weight_to_find)
if index_found_by_weight != -1:
    print(f"Chocolate with weight {weight_to_find} found at index {index_found_by_weight}: {chocolates_by_weight[index_found_by_weight]}")
else:
    print(f"Chocolate with weight {weight_to_find} not found.")

# Searching for a chocolate by price
price_to_find = 1.50
index_found_by_price = find_chocolate_by_attribute(chocolates_by_price, 'price', price_to_find)
if index_found_by_price != -1:
    print(f"Chocolate with price {price_to_find} found at index {index_found_by_price}: {chocolates_by_price[index_found_by_price]}")
else:
    print(f"Chocolate with price {price_to_find} not found.")